---
  header_logo_url:  http://Dermaptera.archive.speciesfile.org/HomePage/Dermaptera/img_Logo/SiteLogo.jpg
  header_logo_text: Dermaptera Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
