---
  project_name: "Dermaptera Species File"
  project_citation: "Heidi Hopkins, Michael D. Maehr, Fabian Haas, & Lesley S. Deem. Dermaptera Species File. Version 5.0/5.0. [retrieval date]. <http://Dermaptera.SpeciesFile.org>"
  project_authors: "Hopkins, H., Maehr, M.D., Haas, F. & Deem, L.S."
  project_url: "https://dermaptera.speciesfile.org"
  project_old_url: "https://dermaptera.archive.speciesfile.org" 
  focal_taxon: "dermaptera"
  focal_taxon_common_name: "earwigs"
  contact_email: "cockroachdoc@gmail.com"
